Remove Ranorex and Selocity
extjs/RxSe-java-data-driven-sample pull request #1
Opened 2020-09-10 05:51 UTC by prem-celestial

I have removed the Ranorex and Selocity from the repository and also change the demoshop links. Kindly review and merge the same.

2020-09-10 14:27 UTC, niharsawant commented on README.md
> +# Sencha WebtestIt Data-driven testing sample
WebTestIt

2020-09-10 14:28 UTC, niharsawant requested changes
WebtestIt -> WebTestIt

2020-09-11 05:12 UTC, prem-celestial commented
> WebtestIt -> WebTestIt
Done.
cc: @niharsawant

2020-09-11 11:46 UTC, niharsawant approved these changes

2020-09-11 11:46 UTC, merged